spring:
  application:
    name: tlias-web-management
  # 数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias?useSSL=false
         &allowPublicKeyRetrieval=true
         &serverTimezone=Asia/Shanghai&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '050926'

# mybatis配置：进行日志输出
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
